# PYTHON CODE: 
# Python version 3.8.10
# 
# ENGLISH:
# Code to print a nested dictionary.
#
# ESPERANTO:
# Kodo por presi vortaron (nestita).

# -*- coding: utf-8 -*-
"""iterate_through_dictionary.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1KtbAnTPP4i2XiNuLlgSPnL88ob-9jPdT
"""

# DEVELOPMENT: Python main code
#
# iterate through a dictionary and print the contents
#
def my_print_dict(d): 
    for k, v in d.items(): 
        if isinstance(v, dict): 
            my_print_dict(v) 
        else: 
            print("{0} : {1}".format(k, v)) 

#
# TEST: test code
#
print("Let us print the first dictionary.\n")
mydict = { 5 : "a", 6 : "b", 7 : "c"}

my_print_dict(mydict)

print("\n\nLet us print the second dictionary.\n")

myseconddict = { 1 : "a", 2 : "b", 3 : "c", 4 : mydict}

my_print_dict(myseconddict)
